export const sagaActions = {
  SAGA_FETCH_FEED: 'SAGA_FETCH_FEED',
  SAGA_FETCH_USER: 'SAGA_FETCH_USER',
  SAGA_LOGIN: 'SAGA_LOGIN',
  SAGA_EDIT_PROFILE: 'SAGA_EDIT_PROFILE',
  SAGA_SAVE_RECIPE: 'SAGE_SAVE_RECIPE'
};
